# Example 1

In [22]:
a = np.arange(15).reshape(3, 5)

In [23]:
a.shape

(3, 5)

In [24]:
a.ndim

2

In [25]:
a.size

15

In [26]:
a.dtype

dtype('int64')

In [27]:
a.itemsize

8

In [28]:
type(a)

numpy.ndarray

In [29]:
b = np.array([6, 7, 8])

In [30]:
b.size

3

In [31]:
type(b)

numpy.ndarray

# Array Creation

In [33]:
a = np.array([2,3,4])
a.dtype

dtype('int64')

In [34]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [37]:
# transforms sequence of sequences into 2 dimensional arrays
b = np.array([(1, 2), (3, 4)])
print(b)
b.dtype

[[1 2]
 [3 4]]


dtype('int64')

In [38]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

# Zeros, Ones, Empty
- By default, the type is float64

In [40]:
np.zeros( (3,4) )

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [41]:
np.ones( (2,3,4), dtype=np.int16 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [43]:
np.empty( (2,3) )  # unitialized; output may vary

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

# Arange

In [47]:
np.arange(20, 30, 5)

array([20, 25])

In [48]:
np.arange(2, 3, 0.3)

array([ 2. ,  2.3,  2.6,  2.9])

# Linspace

In [49]:
from numpy import pi

In [51]:
np.linspace( 0, 2, 9 ) # that receives as an argument the number of elements that we want, instead of the step

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [52]:
x = np.linspace( 0, 2*pi, 100 )

In [53]:
y = np.sin(x)

# Basic Operations

In [62]:
a = np.array( [20,30,40,50] )
a

array([20, 30, 40, 50])

In [63]:
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [64]:
c = a-b
c

array([20, 29, 38, 47])

In [65]:
b ** 2

array([0, 1, 4, 9])

In [66]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [67]:
a < 35

array([ True,  True, False, False], dtype=bool)

In [70]:
# The * operator operates element wise
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )
C = A * B
C

array([[2, 0],
       [0, 4]])

In [72]:
# use the .dot function to get the matrix product
A.dot(B)

array([[5, 4],
       [3, 4]])

In [73]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

In [80]:
a = np.ones((2,3), dtype=int)
print(a)
a *= 3
print(a)

[[1 1 1]
 [1 1 1]]
[[3 3 3]
 [3 3 3]]


In [84]:
b = np.random.random((2,3))
print(b)
b += a
print(b)

[[ 0.28168879  0.94789832  0.62956266]
 [ 0.48284671  0.23557425  0.64289072]]
[[ 3.28168879  3.94789832  3.62956266]
 [ 3.48284671  3.23557425  3.64289072]]


In [85]:
a = np.random.random((2,3))
print(a)
print(a.sum())
print(a.min())
print(a.max())

[[ 0.03667004  0.77832547  0.65312521]
 [ 0.63326678  0.13796214  0.32705682]]
2.5664064537
0.036670041826
0.778325467913


In [89]:
# An operation can be applied to a specific axis of an array
b = np.arange(12).reshape(3,4)
print(b)
# sum of each column
print(b.sum(axis=0))
# min of each row
print(b.min(axis=1))
# cumulative sum of each row
print(b.cumsum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[0 4 8]
[[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


# Universal Functions

In [91]:
B = np.arange(3)
B

array([0, 1, 2])

In [92]:
np.exp(B)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [93]:
np.sqrt(B)

array([ 0.        ,  1.        ,  1.41421356])

In [94]:
C = np.array([2., -1., 4.])

In [95]:
np.add(B, C)

array([ 2.,  0.,  6.])

# Indexing, Slicing and Iterating

In [97]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [98]:
a[2]

8

In [99]:
a[2:5]

array([ 8, 27, 64])

In [102]:
# equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to -1000
a[:6:2] = -1000
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

In [107]:
a[ : :-1] # Reverse a

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000])

In [108]:
for i in a:
    print(i ** (1/3.))

nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


/Users/ddigges/anaconda/envs/python3/lib/python3.5/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in power
  from ipykernel import kernelapp as app


In [109]:
def f(x,y):
    return 10*x+y

In [110]:
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [111]:
b[2,3]

23

In [112]:
b[0:5, 1] 

array([ 1, 11, 21, 31, 41])

In [113]:
b[:,1]

array([ 1, 11, 21, 31, 41])

In [115]:
b[1:3, : ]

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [116]:
b[-1]

array([40, 41, 42, 43])

In [117]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                 [ 10, 12, 13]],
                [[100,101,102],
                 [110,112,113]]])

In [118]:
c.shape

(2, 2, 3)

In [119]:
c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [120]:
c[...,2]

array([[  2,  13],
       [102, 113]])

# Shape Manipulation

In [122]:
a = np.floor(10*np.random.random((3,4)))
a

array([[ 3.,  5.,  8.,  0.],
       [ 4.,  2.,  3.,  4.],
       [ 3.,  7.,  1.,  0.]])

In [123]:
print(a.shape)

(3, 4)


In [124]:
#flatten the array
a.ravel()

array([ 3.,  5.,  8.,  0.,  4.,  2.,  3.,  4.,  3.,  7.,  1.,  0.])

In [125]:
a

array([[ 3.,  5.,  8.,  0.],
       [ 4.,  2.,  3.,  4.],
       [ 3.,  7.,  1.,  0.]])

In [128]:
a.shape = (6, 2)
a

array([[ 3.,  5.],
       [ 8.,  0.],
       [ 4.,  2.],
       [ 3.,  4.],
       [ 3.,  7.],
       [ 1.,  0.]])

In [130]:
# Transpose
a.T

array([[ 3.,  8.,  4.,  3.,  3.,  1.],
       [ 5.,  0.,  2.,  4.,  7.,  0.]])

In [139]:
# returns a new array with the modified shape
a.reshape(2, 6)

array([[ 3.,  5.,  8.,  0.,  4.,  2.],
       [ 3.,  4.,  3.,  7.,  1.,  0.]])

In [140]:
a    

array([[ 3.,  5.],
       [ 8.,  0.],
       [ 4.,  2.],
       [ 3.,  4.],
       [ 3.,  7.],
       [ 1.,  0.]])

In [141]:
# modifies the array itself
a.resize(6, 2)
a

array([[ 3.,  5.],
       [ 8.,  0.],
       [ 4.,  2.],
       [ 3.,  4.],
       [ 3.,  7.],
       [ 1.,  0.]])

In [143]:
# Giving -1 in a reshaping operation automatically calculates the other dimensions
a.reshape(4, -1)

array([[ 3.,  5.,  8.],
       [ 0.,  4.,  2.],
       [ 3.,  4.,  3.],
       [ 7.,  1.,  0.]])

# Stacking together different arrays

In [144]:
a = np.floor(10*np.random.random((2,2)))
a

array([[ 8.,  6.],
       [ 9.,  8.]])

In [145]:
b = np.floor(10*np.random.random((2,2)))
b

array([[ 0.,  8.],
       [ 8.,  6.]])

In [147]:
np.vstack((a,b))

array([[ 8.,  6.],
       [ 9.,  8.],
       [ 0.,  8.],
       [ 8.,  6.]])

In [148]:
np.hstack((a,b))

array([[ 8.,  6.,  0.,  8.],
       [ 9.,  8.,  8.,  6.]])

In [150]:
# The function column_stack stacks 1D arrays as columns into a 2D array.
from numpy import newaxis
np.column_stack((a,b))

array([[ 8.,  6.,  0.,  8.],
       [ 9.,  8.,  8.,  6.]])

In [152]:
a = np.array([4.,2.])
b = np.array([2.,8.])

In [153]:
a[:,newaxis]

array([[ 4.],
       [ 2.]])

In [154]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[ 4.,  2.],
       [ 2.,  8.]])

In [155]:
np.vstack((a[:,newaxis],b[:,newaxis]))

array([[ 4.],
       [ 2.],
       [ 2.],
       [ 8.]])

# Splitting one array into several smaller ones

In [157]:
a = np.floor(10*np.random.random((2,12)))
a

array([[ 7.,  9.,  6.,  7.,  8.,  2.,  4.,  3.,  9.,  0.,  5.,  1.],
       [ 7.,  5.,  5.,  9.,  4.,  8.,  3.,  6.,  6.,  1.,  3.,  8.]])

In [158]:
np.hsplit(a,3) 

[array([[ 7.,  9.,  6.,  7.],
        [ 7.,  5.,  5.,  9.]]), array([[ 8.,  2.,  4.,  3.],
        [ 4.,  8.,  3.,  6.]]), array([[ 9.,  0.,  5.,  1.],
        [ 6.,  1.,  3.,  8.]])]

In [159]:
np.hsplit(a,(3,4)) # split after 3rd and 4th column

[array([[ 7.,  9.,  6.],
        [ 7.,  5.,  5.]]), array([[ 7.],
        [ 9.]]), array([[ 8.,  2.,  4.,  3.,  9.,  0.,  5.,  1.],
        [ 4.,  8.,  3.,  6.,  6.,  1.,  3.,  8.]])]

# Copies and Views

In [162]:
a = np.arange(12)
b = a
print(b is a)

b.shape = (3, 4)
print(a.shape)

True
(3, 4)


# View or Shallow Copy

In [170]:
c = a.view()
print(c is a)
print(c.base is a) # c is a view of the data held in a
print()

False
True



In [171]:
c.shape = 2,6 
a.shape    

(3, 4)

In [173]:
c[0,1] = 12345 #a's data also changes
a

array([[    0, 12345,     2,     3],
       [    4,     5,     6,     7],
       [    8,     9,    10,    11]])

In [176]:
# slicing an array returns a view of it
s = a[ : , 1:3]
s

array([[12345,     2],
       [    5,     6],
       [    9,    10]])

In [178]:
s[:] = 10
s

array([[10, 10],
       [10, 10],
       [10, 10]])

In [179]:
#a will also have changed
a

array([[ 0, 10, 10,  3],
       [ 4, 10, 10,  7],
       [ 8, 10, 10, 11]])

In [181]:
# copy method makes a deep copy of the array and it's data
d = a.copy()
print(d is a)
print(d.base is a)
d[0,0] = 9999
print(a)

False
False
[[ 0 10 10  3]
 [ 4 10 10  7]
 [ 8 10 10 11]]


# Indexing with arrays of indices

In [183]:
a = np.arange(12)**2   
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [186]:
i = np.array( [ 1,1,3,8,5 ] ) 
a[i]

array([ 1,  1,  9, 64, 25])

In [187]:
j = np.array( [ [ 3, 4], [ 9, 7 ] ] )
a[j]

array([[ 9, 16],
       [81, 49]])

In [189]:
# When the indexed array a is multidimensional, a single array of indices refers to the first dimension of a.
palette = np.array( [ [0,0,0],                # black
                       [255,0,0],              # red
                       [0,255,0],              # green
                       [0,0,255],              # blue
                       [255,255,255] ] )       # white

In [192]:
image = np.array( [ [ 0, 1, 2, 0 ],           # each value corresponds to a color in the palette
                     [ 0, 3, 4, 0 ]  ] )

In [197]:
# We can also give indexes for more than one dimension.
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [198]:
i = np.array( [ [0,1],                        # indices for the first dim of a
                 [1,2] ] )

In [199]:
j = np.array( [ [2,1],                        # indices for the second dim
                 [3,3] ] )

In [202]:
a[i,j]

array([[ 2,  5],
       [ 7, 11]])

In [203]:
a[i, 2]

array([[ 2,  6],
       [ 6, 10]])

In [204]:
a[:,j]

array([[[ 2,  1],
        [ 3,  3]],

       [[ 6,  5],
        [ 7,  7]],

       [[10,  9],
        [11, 11]]])

In [205]:
l = [i,j]
a[l]

array([[ 2,  5],
       [ 7, 11]])

In [206]:
# search the maximum values of time dependent series
time = np.linspace(20, 145, 5)  
time

array([  20.  ,   51.25,   82.5 ,  113.75,  145.  ])

In [208]:
data = np.sin(np.arange(20)).reshape(5,4)
data

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784],
       [-0.28790332, -0.96139749, -0.75098725,  0.14987721]])

In [215]:
ind = data.argmax(axis=0)

In [211]:
ind

array([2, 0, 3, 1])

In [212]:
time_max = time[ ind] 

In [218]:
data_max = data[ind, range(data.shape[1])] # => data[ind[0],0], data[ind[1],1]...
data_max

array([ 0.98935825,  0.84147098,  0.99060736,  0.6569866 ])

In [219]:
time_max

array([  82.5 ,   20.  ,  113.75,   51.25])

In [220]:
np.all(data_max == data.max(axis=0))

True

In [222]:
# You can also use indexing with arrays as a target to assign to:
a = np.arange(5)
a[[1,3,4]] = 0
a

array([0, 0, 2, 0, 0])

In [223]:
#  when the list of indices contains repetitions, the assignment is done several times, leaving behind the last value
a = np.arange(5)
a[[0,0,2]]=[1,2,3]
a

array([2, 1, 3, 3, 4])

In [224]:
a = np.arange(5)
a[[0,0,2]]+=1
a

array([1, 1, 3, 3, 4])

# Indexing with Boolean Arrays


In [225]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [226]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [227]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [228]:
# this is useful in assignments
a[b] = 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

In [229]:
# The second way of indexing with booleans is more similar to integer indexing; 
# for each dimension of the array we give a 1D boolean array selecting the slices we want.
a = np.arange(12).reshape(3,4)
b1 = np.array([False,True,True])  
b2 = np.array([True,False,True,False])

In [230]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [231]:
a[b1]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [233]:
a[ :,b2]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [234]:
a[b1,b2]    

array([ 4, 10])